// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNn0h-i0PwjQXfgJiT06xYYgSIGi0WLM',
    appId: '1:659593446855:web:7b34ddc2e7dbe860aa85e2',
    messagingSenderId: '659593446855',
    projectId: 'whalestestproject',
    authDomain: 'whalestestproject.firebaseapp.com',
    storageBucket: 'whalestestproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQzTTrEGHHbIOPXOkRnWsQ47bt4q4Zb4',
    appId: '1:659593446855:android:b0926761fc2c8ea0aa85e2',
    messagingSenderId: '659593446855',
    projectId: 'whalestestproject',
    storageBucket: 'whalestestproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Gv_bJH4XKS1U2PZnELPg7daIvsk2kCc',
    appId: '1:659593446855:ios:e6ca8a718e4f529aaa85e2',
    messagingSenderId: '659593446855',
    projectId: 'whalestestproject',
    storageBucket: 'whalestestproject.appspot.com',
    iosClientId: '659593446855-tg282tl0er4puqcdm4au6gdhih02eeqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Gv_bJH4XKS1U2PZnELPg7daIvsk2kCc',
    appId: '1:659593446855:ios:a1874f14341a9923aa85e2',
    messagingSenderId: '659593446855',
    projectId: 'whalestestproject',
    storageBucket: 'whalestestproject.appspot.com',
    iosClientId: '659593446855-ubtn0432ht7f7jifok058gdtv8p5vc3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
